package lesson18.homeworks

fun main() {
    println("Холодильник")
    val fridge = Fridge()
    fridge.powerOn()
    fridge.open()
    fridge.setTemperature(5)
    fridge.programAction("Режим заморозки")
    fridge.execute()
    fridge.close()
    fridge.powerOff()
    
    println("\n Стиральная машина")
    val washingMachine = WashingMachineDevice()
    washingMachine.powerOn()
    washingMachine.connectToWaterSupply()
    washingMachine.connectToDrain()
    washingMachine.open()
    washingMachine.close()
    washingMachine.setTemperature(60)
    washingMachine.programAction("Стирка хлопок 60C")
    washingMachine.execute()
    washingMachine.getWater(40)
    washingMachine.drain()
    washingMachine.powerOff()
    
    println("\n Чайник ")
    val kettle = Kettle()
    kettle.powerOn()
    kettle.fillWater(1500)
    kettle.setTemperature(100)
    kettle.startMonitoring()
    kettle.programAction("Кипячение")
    kettle.execute()
    kettle.powerOff()
    
    println("\n Духовка ")
    val oven = Oven()
    oven.powerOn()
    oven.open()
    oven.close()
    oven.setTemperature(180)
    oven.programAction("Конвекция")
    oven.execute()
    oven.powerOff()
    
    println("\n Попытка использования при выключенном питании ")
    val testFridge = Fridge()
    testFridge.setTemperature(5)
    testFridge.programAction("Тест")
}
